name: artifacts

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: aergus/latex

    steps:
    - uses: actions/checkout@v2
    
    - name: Install orglearn
      run: |
        apt-get update
        apt-get install -y python3-pip
        python -m pip install --upgrade pip
        pip install orglearn

    - name: Generate pdfs
      run: |
        find . -name "*.org" -exec orglearn pdf {} ';'
        
    - name: Pack the whole repo for now
      run: |
        zip -r artifacts.zip *
        
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts.zip
        path: artifacts.zip
